version: '2'
services:

  phonebook-mysql:
    container_name: phonebook-mysql
    image: muhammadhanif/phonebook:mysql

  phonebook-flask:
    container_name: phonebook-flask
    image: muhammadhanif/phonebook:flask
    ports:
      - "8181:8181"
    working_dir: /hnf/source_code
    command: python server.py
    links: 
    - phonebook-mysql

